### ISSUE TITLE
Use of " And " with numeric word and symbols are different

### ISSUE THREAD

**Issue by Manish-210** [scrapinghub/number-parser#58]
For the given two examples, the results are different but they should be similar.
```
>>> parse("I will eat banana and apple in two and three minutes")
'I will eat banana and apple in 2 and 3 minutes'
>>> parse("I will eat banana and apple in two and 3 minutes")
'I will eat banana and apple in 2 3 minutes'
```

**Comment by noviluni** [comment]
Hi @Manish-210! Thank you for opening the issue.

This is fixed in master. It was originally reported here: https://github.com/scrapinghub/number-parser/issues/30 and fixed here: https://github.com/scrapinghub/number-parser/pull/49

I will close this issue. It will be fixed in the package as soon as we release a new version. Thanks for the feedback!
